import type { Usuario, Proveedor, Tarea, Estadisticas } from "@/types";

export const mockUsuarios: Usuario[] = [
  {
    id: "1",
    nombre: "María González",
    email: "maria@example.com",
    telefono: "+34 600 123 456",
    tareasCompletadas: 12,
    horasAhorradas: 18,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    nombre: "Juan Pérez",
    email: "juan@example.com",
    telefono: "+34 600 234 567",
    tareasCompletadas: 8,
    horasAhorradas: 12,
    createdAt: new Date("2024-02-20"),
  },
];

export const mockProveedores: Proveedor[] = [
  {
    id: "1",
    nombre: "Carlos Martínez",
    email: "carlos@example.com",
    telefono: "+34 600 345 678",
    dni: "12345678A",
    nivel: "oro",
    puntuacion: 4.9,
    serviciosCompletados: 156,
    serviciosOfrecidos: ["recados", "mascotas"],
    zonasTrabajo: ["Barcelona Centro", "Eixample"],
    disponible: true,
    tasaAceptacion: 95,
    cancelaciones: 2,
    tiempoRespuesta: 15,
    ingresos: 3450,
    createdAt: new Date("2023-06-01"),
  },
  {
    id: "2",
    nombre: "Ana López",
    email: "ana@example.com",
    telefono: "+34 600 456 789",
    dni: "23456789B",
    nivel: "plata",
    puntuacion: 4.7,
    serviciosCompletados: 45,
    serviciosOfrecidos: ["ayuda_domestica", "recados"],
    zonasTrabajo: ["Gracia", "Sarrià"],
    disponible: false,
    tasaAceptacion: 90,
    cancelaciones: 1,
    tiempoRespuesta: 25,
    ingresos: 1250,
    createdAt: new Date("2024-01-10"),
  },
];

export const mockTareas: Tarea[] = [
  {
    id: "1",
    usuarioId: "1",
    usuario: mockUsuarios[0],
    proveedorId: "1",
    proveedor: mockProveedores[0],
    categoria: "recados",
    titulo: "Recoger paquete en correos",
    descripcion: "Necesito que alguien recoja un paquete en la oficina de correos de Paseo de Gracia",
    direccion: "Paseo de Gracia, 123",
    zona: "Eixample",
    horarioPreferido: "Mañana entre 10:00-13:00",
    precio: 15,
    estado: "completada",
    valoracion: 5,
    comentario: "Excelente servicio, muy rápido y amable",
    createdAt: new Date("2024-11-15"),
    completedAt: new Date("2024-11-15"),
  },
  {
    id: "2",
    usuarioId: "1",
    usuario: mockUsuarios[0],
    categoria: "mascotas",
    titulo: "Paseo de perro",
    descripcion: "Necesito que paseen a mi perro durante 1 hora",
    direccion: "Calle Valencia, 234",
    zona: "Eixample",
    horarioPreferido: "Tarde 18:00-19:00",
    precio: 12,
    estado: "pendiente",
    createdAt: new Date("2024-11-18"),
  },
  {
    id: "3",
    usuarioId: "2",
    usuario: mockUsuarios[1],
    proveedorId: "2",
    proveedor: mockProveedores[1],
    categoria: "ayuda_domestica",
    titulo: "Organizar armario",
    descripcion: "Ayuda para doblar ropa y organizar armario",
    direccion: "Calle Aragón, 456",
    zona: "Eixample",
    horarioPreferido: "Sábado mañana",
    precio: 25,
    estado: "en_curso",
    createdAt: new Date("2024-11-17"),
  },
];

export const mockEstadisticas: Estadisticas = {
  tareasHoy: 24,
  tareasMes: 487,
  proveedoresActivos: 45,
  usuariosActivos: 312,
  ingresosMes: 8950,
};
